/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomNav: typeof import('./src/components/customNav/customNav.vue')['default']
    LoadMore: typeof import('./src/components/loadMore/loadMore.vue')['default']
    MenuPopup: typeof import('./src/components/customNav/components/menu-popup.vue')['default']
    Modal: typeof import('./src/components/modal/index.vue')['default']
    NumberBox: typeof import('./src/components/numberBox/numberBox.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutGrid: typeof import('nutui-uniapp/components/grid/grid.vue')['default']
    NutGridItem: typeof import('nutui-uniapp/components/griditem/griditem.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutTabPane: typeof import('nutui-uniapp/components/tabpane/tabpane.vue')['default']
    NutTabs: typeof import('nutui-uniapp/components/tabs/tabs.vue')['default']
    NutTextarea: typeof import('nutui-uniapp/components/textarea/textarea.vue')['default']
    Popup: typeof import('./src/components/popup/popup.vue')['default']
    SelectMultiple: typeof import('./src/components/selectMultiple/selectMultiple.vue')['default']
    SelectPerson: typeof import('./src/components/selectPerson/index.vue')['default']
    SingleSelect: typeof import('./src/components/singleSelect/singleSelect.vue')['default']
    Tabbar: typeof import('./src/components/tabbar/tabbar.vue')['default']
    UploadFile: typeof import('./src/components/uploadFile/uploadFile.vue')['default']
    UploadImage: typeof import('./src/components/uploadImage/uploadImage.vue')['default']
    Vue3Echarts: typeof import('./src/components/vue3-echarts/vue3-echarts.vue')['default']
  }
}
